ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "vault-issuer"
    cert-manager.io/common-name: "monitoring.hk.home"
  hosts:
  - monitoring.hk.home
  tls:
  - hosts:
    - monitoring.hk.home
    secretName: grafana-cert

persistence:
  enabled: true

adminUser: admin
adminPassword: change_me_password

apiVersion: 1

datasources:
  apiVersion: 1
  datasources:
  - name: Loki
    type: loki
    url: http://loki.grafana.svc:3100
    jsonData:
      timeout: 60
      maxLines: 1000