apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn