apiVersion: v1
kind: Secret
metadata:
    name: rootCA
    namespace: default
data:
    ca.crt: ENC[AES256_GCM,data:U3nc6RR3ggj7Lp2ulvFZTb6xoXQYVt28hgs4nbqJvT8FqoqtHk2lyxYtEYHmC45OFSVii0HrmOany2VkQuW3LHGcaunWIUYUIOxfnZvrqYk1VVquHNOHpjWYCcIk3nY6e4WzQ96YJtJhSmAxiYy4pemh7cSmotc6k+nD1f7rbEf7V+tgx/U1ZdSK4mhBJwb8T0WKXHnNAAII+2d9SdV3bPK3N8nDsBs51v6uGAPmXH6rBFN/at/4mc7JBHjBpYF+Y6Ah7frQHfLyMGqrLnFGoijfZAxVKR4+R+pGhIVdMrcLBSXf3Ijaije1H8BmSdbe1muRFLMvAShDsux9dEADS1nQyuf/tnrBIRnk/i56+AYbTHIgdU8xgDZiZwSHTvN38u3CWKxw3fb5qFpL+1uEmfqmUh7j0a1Gnl4gVVf9yEeoK1VYTmigP62q4dTnruiDf05t5Yc1iDJ2JY36GOLu+9RZsi1yKqdFhQWx+ThRlos20+Z887+G7Z9a4fAPcgSvS2XL6vs9/s7unio4BVRP5NENPuh/F8jLOFeQ+LvG6lqYqTQA+LxACLY3DgFn9xKJJkReYqyGl3zLBtwWWUwwAJXxcYrQ2nqOjNXWob7RP8GvB3EXfwfKUFgE9NR415LrgDQIXEDyRdzlGXEbCnGBsuoR/qdC2ZqM/lhU3XEmm1/YB9MSNLGqVxuxg0Y7/QNUk7OCGyqt/w82ceD8BxK+GLSFTuDiKvezgPefwt+v2/6Ak2+AOUBAplyLLUEvpC7LFdl4VXBSsWbGJIz21k0FXbI/S1shRAPBmWn8diJM2MGn6ha5P0oJEyoeFe5l37og1DC/I/iVsHTM8UILAki9uS2AI8RwUaOyZALNTPjBGSs+SFEceZrccabzgxh3IrLOah/CQQj61wv8r4Nf+fv5tB8p7BjB1WGY1DYZUzkir+HITSrng3OjRTxdhZ91WCJmgYwIS+4yomPdOysUZ1L9hY1dJzSL7+lLoMSv9iU=,iv:e85s8w6p7qsjARvqfsF4UYQjHM7+mfIjSGsMxQBDZ08=,tag:NkQ3xd/npqitOh/10ZmODg==,type:str]
sops:
    lastmodified: "2026-02-28T10:53:58Z"
    mac: ENC[AES256_GCM,data:L/CpUtbCSz9RR6wWgOaDv30saRxu0xTzb16aL4+14pe0wTNkfuEF4qFkHtf6MV0Pwfj35OW7/QrR7hDD4NU7VeN1UcS+4VY70B2ip3CZIhGxxIL8iQkBVdBzi6LldA+gPExuvIzlRC5SICbgrY1jrXhG1AJg+Gdkl3cVwBjvF98=,iv:aXFtUyn7IfzZwMTVjdVHN0GnJ6trkddIlXvVEcf/h/0=,tag:1fAjGm84CGV6e7PEuXsZAA==,type:str]
    pgp:
        - created_at: "2026-02-28T10:53:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/WlvTeS7ZmVAQ/9HLRRI+26h1CqWbhXPmF6Fi68JAVMeADZfh5dgvI63F5N
            VGEAfWGSpyEgmTlKTDZohSDySAWITJPLu91KAkm9rWIF9mPjG4qdg9olS+WI068K
            2E1oMzGhDhRNaMjuJbkNprnENl0LWW/1mee94DHdKa4Zu7VNhg+1Dgqw/yaEjys3
            GZu6ejdV8PoSOQothbgRrym+tq9e9mEccu6BOQMR2iMt2X2LLjW46GUA+QgHl1zN
            lI+8bKTYONBDy69vTFLvyB46QHMI1zEqQajn/BQ157HDKzOh/C62uStXRMeJ8tfY
            dVN2sZm6VVjQ8xM6bQwfw6mDXdRt+ODVA2GxNcHqfFpKcqA4n1at2VMup4G9s82G
            amdEP/lRfeOjwuL39Yr5u47nBwRUtlRjHt+P99ytWUiniG+75NsxpCeYVuYbEqyl
            0zqcT+MnjV7lNc4lySuzxcXBr3i0T92E9MCIPChJZJ9wcPqGW9eG47ABcSnD2uwa
            B36FhlkfgKT4+pgYR0AHWXSf6tGinTtPsDBodoFHUb4NskF8ovndmpBaaTkAdGm7
            SEFd1oB19o545ROC5HDOcKKDsIZob9XCV0l4kAbA1iehW64OkuIJNzqS5F1UBKBe
            Emm74ZLpBGS6wrQm9lUSgjs2be3U2Cedvi7F19ft2Qosagm2PJdng1UJkZzFb9jS
            XgHANNLPU3K3n0TYo+0ATih7thfjyv69gWPNiZZ0TCKKAakO0uVf2WEAtKh4R+qL
            WJfyb6c5LVZInYb+yTlp/XtTNUVSHdeCrdotclvjPyzCrvJhPSldkNRUBwHXPr4=
            =Nf5z
            -----END PGP MESSAGE-----
          fp: D64FA5FE2BB2D5F3D250F1A7C009D75505A44188
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
