apiVersion: v1
kind: Secret
metadata:
    name: rootCA
    namespace: default
data:
    ca.crt: ENC[AES256_GCM,data:HW9WqXiwl+DvCw1JO0F6Nh9+axSVJ1KEQt6Qrs55pfqdUcRKPiJ0VpF/EuHmnCc1G4xwNxz4DAh/6XXVLIhSTriwsu723ormGa2cAK3MOwrWqqqOgYQsE3DLO2LiZ09/Q4k96f5XsNqZQzeC61PFwEasWNYw+fW3mtH08IibEC5jau0bVperlkuT7NS7+SBeFYdAvbYHHf5yldBpT+YsMwzkRK+eDNzQ5uGNGr0pEAT/nSHq/eYRJ7LbDv5PPJXiDSZqFXYkrT6SFBmsUTi360qn6NxM03xPCS0nQLscr3MFxtfd7Ot9pisitlZ9pofi6g7o23RPyIWU2GALO8qcAYOc1dTLr2Sb9HUu4MHXuV6ZReET8KYEKQqUIioAr2GIS1r4/2LeJ7q7GjpEL+stSB1wLEwVXSdfJRDbCs+/6jRaTudiCjt84cNyAO2tzGgTrOGVXLcpvAQPwYkwnD6xukG0JCCwUpRTN/B8c4BA3oGQQEqM3jpaIISeH62lEAnsc4/UFRiERn4UMnMwExdAnd57zPMh0TZweBEDnMzpF+eHYcfI8FseIsNPXZw6kHfAa1xJeHXClHd/VeynLDKZRTUT6IqUo1+Bxbi5X9N2KlVvZFI8wXbZngK147QmZhXT4sPYivnEbwdeAVYBXsYnA+4bK/gGsQCcx82U4v6uytXUV2GbjuBOTh9XropSSVXeAfczWBGlgzATcYVEtxWzSlE5Zu9axsxVlx5CmvN0NFVQ/EIkWu7bUeZitiZc/lPvZ+SydYuV5p3VbC3gYptx4+r+5MKYAmDeZrV0zPpJEzISPsL9mBWRz4pbwvM/vSDgN8Luxj6D/aPOl62U6YtLjx0B8RrrG2sVK5RKkLd0shhDwclGx3ShfZJHk32fkdIcycaj4uUjiZTwdUDBOyW88bE4Wd2YZVzSZr79kf1T85gR0/elJK4NvBKvv2hKqpGWSqBhaUIx7vLYQHD+T+dEbRF6LIfPz0cYEg32e10=,iv:iitco6alVew99us77cQI+pyOZWfH8LJ0TsiUqU8Chm4=,tag:EGI2dIu0+jFpNLc2k8BU6Q==,type:str]
sops:
    lastmodified: "2026-02-27T18:02:12Z"
    mac: ENC[AES256_GCM,data:PaJyUlyYGFI90FWGRT+7H2ltZcY7qTetNVc2bt1l2qJ6GNmZSUF59SxU3HNRruGBa8fxziHKzDsCq9t9xX9CmElB1akRpFgpsyBuC159xNw2lc6yv0Shz3XPY7HA3ab+11h/YpGttGmnu9AAjfNBve7Ry00g8hKJ5boftpvaiAg=,iv:MTO5GE2oNaToV03k6UwNsHPs1RZ9o21voNDcaEmszlU=,tag:C4wr0cnO2lGSWqNeLifa2Q==,type:str]
    pgp:
        - created_at: "2026-02-27T18:02:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/WlvTeS7ZmVAQ//V2lfKW8B5gKvhcYGJF2saX0FfnpoKX3aWgzzG+XeUXQg
            R/XtVp0Vny0DIeiBghDvbjbNV4DoF1QvJbqfWxkeCAP+pYWV1qz2BLdEbIh3ZVvx
            Ayh63Z2CKtDSiSPY31daHmm0kB9a+UBEiYKIfwdeIPXryZn/Q4QDjg2obWATed2V
            EucLKRgCqbNb9gsmvb0qUpNLGX/EnoqwzXkTg8dsbmMHDcxBlqLRmNxSzREQlIPW
            ZhmNpS1xm+YqmQ4EloF7GcRTs8OPUG14kn8dTdv74DLgRmS6zTQLZXMEKN42WGQp
            N/EIbYcA0AAa9lKENxQQzdgcnZQA2SbZfp7KB1nTAMhBkTNCad3ldlul1vi4U9gU
            GkYzo6CUx1EgsF2ymQ9Ga1XThZ54VbRJTStQd2DFB1bizX4Soq8Xte6sz5lPctlA
            L/gnuhE9DvsERNt/KEDr2nOqyEPRB45McS3whxq0cmKsEusvFmrp124H0wOvxfv+
            utHKt5SM7z1e4wis7fgwuHKDX0PL1Rx+ffGY0LVSnFyIVLf7otIqqdQJfaUUJ34D
            xnq7d470PhiYxfuxgUNdenzL0phTco4tNTZdJNS7zuNNjaPaccqasjQmbblhNiM3
            MFCpAVPfHgADcGL9G6QJn0sjZ/zb4jJiJG9w1BUJMnVwm7k5PfHyouU5EpHDPEDS
            XgGbuO9IsWudcEItbETDBpL7RR9ZeC+PkZNgH4AYL+Xjr96p7nrFB6McimbAmBBi
            8YEfJyot8/NvMNILr/114IdQitKoBloPbDYHjo9sCqX8SN0A0EQuEGYWHd3dC+Q=
            =mX4v
            -----END PGP MESSAGE-----
          fp: D64FA5FE2BB2D5F3D250F1A7C009D75505A44188
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1