apiVersion: v1
kind: Secret
metadata:
    name: rootCA
    namespace: default
data:
    ca.crt: ENC[AES256_GCM,data:SSHvxFAs6NUzKztlxMf8YH6CBCq5S7RuzsZT4cAqPvdvjWLHOcmBIahu0iOM5NWmr/9p25QBvcVxsslhT0MjV7WwLwuCd7lNOaz8HAULyxsK134t/TPSJPt7Yez0MH8jOQkcd3BZa6gmk97S1JsrDIrsQnJQjfhnKQD1L+1VzHcD+OWH7iOWYpFwur8qQ7IhZta5Eupu/MDG8/E3ZOIm9v5P+bqwaQuRIGTCpDI8vcORm6kOCSCIwMyManaJ/yS2cgs/FKsU08DI9CAKIFv4zpmnZmnNLBHIzQ6H5JwvTxogmFK5UApxjTDaDWTXTVrmej7+9mmHHwlC7bzCEbsdBn/oiXorEIUZlgDn1OhbTbbQbli2+y0023GH5sdiicCE6+DOncZ0/5KPsHPJPENaWqDunFBJ7Y5B/EoaV3uwVb3d4Wn9t8XmxZ32weNtwda+nbM3Rc5y+Ytgyy3IFadhqJwzWrQmrz2rPW3XdmJq/dqHEAx8pJyqUJbrj8rdZvtx2HYAslWjgh3Qrp7Gqh/M8Au7JRFrstB6mjTlLfotqUhCywRDarFPwYSB+SxIOKk9npzsYaAifza8sSOWX34v+Bd/76O61MzAnQ3CZvIVdLDszAuQGt+DCXt6ablN60hL3M/VEO4Pjvu8eHTuLejas5d+5NuhgAoMdqUySffUeQc1eCxBC5gtkg81ErspLVhLkNpRrlIa2DWNxvRCCCfDlqaaxxUTZH9LpnNofHQpw6ZauT9q0NeAe9PVvDKDE8yBp+MxTji0ZIO8toc/32UoFryrLN0FiNz3XC2iMXWbawovM9Qh+Q22P/IEorjtLr3IgpuQCmgTAIYeWX0RzK3Tx/mK6f7bAXN4tYesGlLYMl09oeAloSY2IcJxZZE80Wzudzq9lbWgH1nFzkBjg1SuWdi5trIj6s/z3xERaedosWRrd/YRf2N6a4Bdj3QksThYhpjed8d644yJabZafXM2dZz128hBHXUX7SnFz9zF5z2Eq6E/2ZEUQHPDqVRbQO2zBuiwi/ic5gYdZxPp1LJSyIOw1o/c9BiSE8oml3MVRv9QE2kbA7eHtzXifTdxh4pZE5377ueQs1HpBXZJ5UjXp5sDyM7I1JfA1uXXPJEXXnmvxhZxNnFncY/qvMLQFiwBuClbnqWd6ceI9vIBQuDJ8RH1EjQ7wATC1e/zdts6V7HwgTgg7aFMaz/NydeKjQvb9bIb86XlIxM7b5Y55Wnfiyhi75IXNte3pxcwB7n1zu8WMACxoOiSLatOPiensE/SjIyAxaQzAQIcnyb470+uCPCpcojYNdJ4GD8JQryIQrEPe/KH5m4H2qoqE7LBtxYBUUqhkyJovHo0VBkIYgWtG7s5/Bj4id/6V8vhDw==,iv:ktguVclkoUeEk6uOAooy0FCH25uxPbNZz/Qi01RmWzM=,tag:qZpFLExYJZIkw7ivAxg8ug==,type:str]
sops:
    lastmodified: "2026-02-28T10:56:17Z"
    mac: ENC[AES256_GCM,data:NOulfrlKThalwYbwf2QD3rBaL5P6qigyqLjkL9oUD8P+EJvHJkCdgPWTr7ixJvAjkm2Qfer46wE5PDe/MbRvuzAnogjdBeWJ2mI6RcpqYV2cc8r/AicxsWXbRj0U2APMH/C07KzOYBlvpe+kOpR2EEGkzdKP/QUQPwnakzH73s4=,iv:6hPbUp7MICzKZo/QlRNc8nJb65tLwCkzKjZxA8pn9hg=,tag:NOwQYplzKt5kWGcaVbYBGQ==,type:str]
    pgp:
        - created_at: "2026-02-28T10:56:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/WlvTeS7ZmVAQ//fwR7ntct5X2pVRQSXvIOM45iX04oJH0C4pnR478rv6LN
            v5+sOM+EUmOQpLyaEO6kLnO2U2vxss+Wlxj+GohFFFmUOgcWVw3VqzAwnCc3iTEQ
            Ise47nqPIt8BJwfkZNVp1HK39QzUa8/f8wdz7Jow/stfDLbROkcdyhaBde3WaPbd
            jWCpDZSZCZitNm4SmwlO3UZe0cUWEUDNJIii/2aiyZs3z1wzlYuxDqNae0RVVnPj
            tTnWqayVdpO1KihWoDLphJ68w3cTKuavLkRy5UGNC/UTsocTva0m0SUvibgbIyzQ
            Fs8r8Pxo4g4Ipg0f0qZ0lzBgfcq4RWNOKuqXlg9bna6syOUiN1/0vcb/b/W/p8Fd
            tGtPil14wwW4kdO8HQ1sir+nmsqx7VNbhlYSXbm0sCDze21JuG9iMNJWicYTz4A3
            VOwBx5gHL5lzsfjE/XDl5aXcrdXv9yfjc16LUZbIgp5vXgVEvhGBmxJdFYXu5lFM
            E9e5gQ6BvzbPej/t7Ob0yT0P45SoBy78NsP6jN1W9mP//2qo3sFvv9tbuzuB8ZgN
            28jKdPX+k4WOk0wQ2+mqHdN3mb68pmrChYHhrzeeH+ikoc/TCfRKbVdmQQhk0/5/
            IhsB9NxjpAImmXnWXcjmG3nM++VSjAmzhqOuEFirdhkyjwarwuXDTcnl5EslazvS
            XgHG/qPXEg0oLu9R1oQB3kTSAFl7gU/nmrWPI28x7g73OHzH7X4LwVozDeMtGZBT
            qe0csn7wgtWe/x3+L1qGJ50u7kfqioSumh7v5ZdQLQ92Ohbm6rvedn1hKv6Y208=
            =PB64
            -----END PGP MESSAGE-----
          fp: D64FA5FE2BB2D5F3D250F1A7C009D75505A44188
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
