apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn
data:
  default-resource.yaml: |
    "backup-target": "nfs://nas.home:/cluster-backup"
    "backup-target-credential-secret": ""
    "backupstore-poll-interval": "3600"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-job
  namespace: longhorn
spec:
  cron: "0 3 * * 5"
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 2