apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: freshrss-data-pvc
      - name: extensions-vol
        persistentVolumeClaim:
          claimName: freshrss-extensions-pvc
      containers:
      - name: freshrss
        image: freshrss/freshrss:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data-vol
          readOnly: false
          mountPath: "/var/www/FreshRSS/data"
        - name: extensions-vol
          readOnly: false
          mountPath: "/var/www/FreshRSS/extensions"
        env: 
        - name: TZ
          value: "Europe/Paris"
        - name: CRON_MIN
          value: "5,25,45"
        - name: LISTEN
          value: "0.0.0.0:8080"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["CHOWN", "SETGID", "SETUID"]
          seccompProfile:
            type: "RuntimeDefault"