apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: freshrss-pvc
      containers:
      - name: freshrss
        image: freshrss/freshrss:latest
        command: ["sh", "-c", "/var/www/FreshRSS/Docker/entrypoint.sh"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vol
          readOnly: false
          mountPath: "/var/www/FreshRSS"
        env: 
        - name: TZ
          value: "Europe/Paris"
        - name: CRON_MIN
          value: "5,25,45"
        - name: LISTEN
          value: "0.0.0.0:8080"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"