apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  PAPERLESS_SECRET_KEY: "/hdXZRTDe2gMC+8D5iHZjHQF52KJPjpmKow38KxDbRCxtN5DCekr0w9Yrc+oTAMzvHcKxklscTcUIr2IfOHRkw=="
  PAPERLESS_REDIS: "redis://redis-db:6379"
  PAPERLESS_TIKA_ENABLED: "false"
  PAPERLESS_TIME_ZONE: Europe/Paris
  PAPERLESS_OCR_LANGUAGE: "fra+eng"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"
  PAPERLESS_URL: "https://paperless.hk.home"
  PAPERLESS_CONSUMPTION_DIR: "/consume"
  PAPERLESS_DATA_DIR: "/static/data"
  PAPERLESS_MEDIA_ROOT: "/static/data"