apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-documents
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn