apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn