apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: external-dns
data:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:04VulKBoJoPZdKwk,iv:Fyhj/4b7lIHphEbO7UTUsDEdfH+I0jTh1zCBdssg/MU=,tag:LO3Q9OROMvgTcsfTWjH4xg==,type:str]
sops:
    lastmodified: "2026-02-10T12:03:58Z"
    mac: ENC[AES256_GCM,data:CYZ1uZ8QniZxYVc3aPH+Qnf6m5xi4oOHdCll85NlUpoi/bLe2+xRZ6lcaXxtv4ubhblAPiAGsRGi7U4oLxKWB/AUqYQmikZ8jQF7oLOMWF3n+O3wdTA3SnMVxgWsYsc3nUJ1iTaAOlT5hBbfrD2UNYJYU+n+biplbddL8DHML8M=,iv:f7XpdfNgJk646+mOvJ6YpKjKVAhMMzNivzYTIScEx9g=,tag:She4Ocq92PeHz/+gMJc1Dw==,type:str]
    pgp:
        - created_at: "2026-02-10T12:03:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/WlvTeS7ZmVAQ/6A2b8v+1S9mg0SciEBaVg/gXQaYpLiXykiBktqlAZC56D
            8xVSxU9FcyIhvN9lAcqrsbJxwm9V4uhfoVQlNEt4TIhxt3gnsNPZ0C5Pg0VzvHSF
            bAOGcMyZAza7Gktb6+THkhG5mzp2cQ+Orb9JK4ZjZss3vjsswWKjddw7jbaD9Y6j
            jOODjK74CPNjYYYrXkPdKOSc1V57lpPYnnGax8QuUSA/M93cEpFOktf7X82Qr7G5
            dMCweuF0SXonF5W4ajK1HRk3nWyaLohxAih/UnWYz23HT/HGBtx3Beqmi5oBTYsF
            DQtkd1NhFBmi8KVwM2WcQS47XB0QQOGXOCRwCyCtHtLJffFVNKoI+wkqZogoZiEt
            HD62JIqhfoSeKqym1wuVY9xgbxrUGIAibs0xEJ6XZ3/yHOHpPrS6R/KHS+1mRUok
            /LAQwwFbrEaF283IJ1sP4ZmUceld4Z6kDpZe5sApBdTAFskxjgLGWe54xkAZgrPG
            j3x/cnQSxV4/cZGgO9EiXP5Yky9SIWoKg0aX0mxkqEIJttrCbGiP2/wxGQJhGPka
            gLuXmqZGGLp5Em3Da7e2H9Ez82nBPergQRILPVsfgG1XA0B8q1Ua4tepJnerLWhj
            ibHoGh/2LZFtsk5gH1RyKjQNARCbCHXJj9VoS9e1FFgZ3sfvG9s1lKLMk2ntglPS
            XgGl5cht9zjJe8nLXYkzyO3W0pBIRPxGzGNURUTRdkAKFSV+QaCanrMc6k5iCwPQ
            Hm0waTcBZAPSOExxGMS6t28JjTdlcAIKSaQHLlxwNBIIFvGNFpmRfPuwHtezX80=
            =cldp
            -----END PGP MESSAGE-----
          fp: D64FA5FE2BB2D5F3D250F1A7C009D75505A44188
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
