apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    name: kyverno
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 12h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 12h
  timeout: 5m
  chart: 
    spec: 
      chart: kyverno
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 12h
  timeout: 5m
  chart: 
    spec: 
      chart: kyverno-policies
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno