apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    name: nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-oci
  namespace: nginx
spec:
  interval: 12h
  url: oci://ghcr.io/nginx/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: nginx-oci
      version: 2.3.1
  interval: 12h