namespace: gitea
configMapGenerator:
  - name: gitea-values
    files: 
    - gitea.values.yaml
  - name: gitea-runner-values
    files: 
    - runner.values.yaml
generatorOptions:
  disableNameSuffixHash: true