namespace: gitea
configMapGenerator:
  - name: gitea-values
    files: 
    - values.yaml=gitea.values.yaml
  - name: gitea-runner-values
    files: 
    - values.yaml=runner.values.yaml
generatorOptions:
  disableNameSuffixHash: true