apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baikal-cert
  namespace: certs
spec:
  commonName: calendar.hk.home
  dnsNames:
  - calendar.hk.home
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  secretName: baikal-cert
  isCA: false
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: baikal-bundle
  namespace: certs
spec:
  sources:
  - useDefaultCAs: false
  - secret:
      name: root-ca
      key: ca.crt
  - secret:
      name: baikal-cert
      key: ca.crt
  - secret:
      name: baikal-cert
      key: tls.crt
  target:
    secret:
      key: tls.cert